### ISSUE TITLE
Got 'ModuleNotFoundError' error

### ISSUE THREAD

**Issue by hayukimori** [IndividualCoder/GamePlus-Editor#3]
### Issue
Unfortunately I had some problems when trying to run the editor in the traditional way, getting the following error:
![image](https://github.com/IndividualCoder/GamePlus-Editor/assets/69482956/3473753f-81ad-4a77-90a8-795e321a3bbf)

### Extra information

(GPE_Environment is a venv, the command executed was the one present in README.md -> `pip3 install GamePlusEditor`)

+ Contents of "./runApp"

```py
#!/usr/bin/env python3 
from GamePlusEditor import RunEditor;

RunEditor()
```

**OS:** EndeavourOS 
**PIP Version (env):** pip 23.2.1
**Python Version**: 3.11

**Comment by IndividualCoder** [comment]
umm....
you have to use python 3.10
this repo uses a module called panda3d which is having some errors with python 3.11
